### ISSUE TITLE
Run the application on Reopened

### ISSUE THREAD

**Issue by petrberan** [xstefank/wildfly-github-bot#119]
Although it's an edge case when it comes to WFLY, I think the checks should be also performed once the PR is reopened. Even though the check should be valid from once the PR is closed as it's not changed, the config could change in the meantime, requiring the checks to be performed again.

Perhaps even on ready_for_review?

Thoughts @xstefank ?

**Comment by xstefank** [comment]
yes on reopen, no on labels

**Comment by petrberan** [comment]
Discussed offline, ready_for_review should be checked as well. I'll take the issue and wait for the #118 to be merged as this issue will fail 2 tests - as tested locally
