### ISSUE TITLE
Refactor test to reduce duplications

### ISSUE THREAD

**Issue by xstefank** [xstefank/wildfly-github-bot#37]
In many tests, we need to define the repository and commit hash for mock to be verified. This information is verified against the prepared test payloads in src/test/resources directory. However, we might need to change these files from time to time. It would be good to have the information that is verified against these file in one place for all tests so we can change it only once and not in almost every test.

**Comment by The-Huginn** [comment]
Replace usage of deprecated API such as following
`mocks.configFileFromString(param1, param2)` should be replaced with `mocks.configFile(param1).fromString(param2)`
