### ISSUE TITLE
Migrate Format checks on Startup of the application

### ISSUE THREAD

**Issue by The-Huginn** [xstefank/wildfly-github-bot#56]
Also we should consider creating a List for formats for individual repositories, in case an application has multiple repositories set up.

**Comment by The-Huginn** [comment]
On hold now, as this app will be used for wildfly only currently.

**Comment by The-Huginn** [comment]
Still would be nice for test isolation in combination with startup event firing

**Comment by The-Huginn** [comment]
+ whenever a PR changing config file gets merged.

However it might get changed directly without PR. This is also problem currently

**Comment by xstefank** [comment]
I think this is done now. Reopen otherwise.
