### ISSUE TITLE
Introduce config file validation

### ISSUE THREAD

**Issue by xstefank** [xstefank/wildfly-github-bot#68]

**Comment by The-Huginn** [comment]
Possibly to validate:
* emails
* `CommitsQuantity#quantity` with `@Pattern`
* `RegexDefinition#pattern` with `@NotNull`
* `Description#regexes` with `@NotNull` or empty

**Comment by xstefank** [comment]
@The-Huginn I believe this is already implemented, let me know otherwise

**Comment by The-Huginn** [comment]
I am not sure. IIRC it should have introduced hibernate-validator to do this on loading the file.
