### ISSUE TITLE
Improve the comment notifying maintainers

### ISSUE THREAD

**Issue by petrberan** [xstefank/wildfly-github-bot#95]
Let's assume I have 2 rules for 2 directories, both notifying the same 2 maintainers A and B. If my commit contains changes for both directories, the github-bot comment will look like this: `/cc @A, @B, @A, @B`.

Either it should be simply `/cc @A, @B` or the comment should contain the rule/directory which triggered the comment, such as
```
/cc
directory_1: @A, @B
directory_2: @A, @B
```

**Comment by xstefank** [comment]
only /cc @A, @B is ok
